Repository BumgeunSong/PR-tracker, pull requests merged in 2022-06, with the labels that each got.

#5 앱 실행 시 로그인 화면이 뜨고 깃허브 버튼을 클릭하면 OAuthManager에게 로그인 요청을 할 수 있음
  PRTracker.xcodeproj/project.pbxproj
  PRTracker/Resource/Assets.xcassets/Images/Contents.json
  PRTracker/Resource/Assets.xcassets/Images/img_logo.imageset/Contents.json
  PRTracker/Resource/Assets.xcassets/Images/img_logo.imageset/img_logo.png
  PRTracker/Resource/Base.lproj/Main.storyboard
  PRTracker/Source/Common/Observable.swift
  PRTracker/Source/Common/ReplaceRootSegue.swift
  PRTracker/Source/Login/View/ViewController.swift
  PRTracker/Source/Login/ViewModel/LoginViewModel.swift
  PRTracker/Source/PR_Listing/View/ListingViewController.swift
  PRTracker/Source/PR_Listing/ViewModel/LabelViewModel.swift
  PRTracker/Source/PR_Listing/ViewModel/ListingViewModel.swift
  PRTracker/Source/PR_Listing/ViewModel/PRTableCellViewModel.swift
  Podfile.lock
Labels: ✨Design, 💡Feature

#20 유효성 검사 로직 수정 + 토큰 획득시 화면 이동 로직 추가
  PRTracker.xcodeproj/project.pbxproj
  PRTracker/Source/Common/NetworkService.swift
  PRTracker/Source/Common/UIViewController+Alert.swift
  PRTracker/Source/Common/View/IntroViewController.swift
  PRTracker/Source/Login/Model/GitHubLoginManager.swift
  PRTracker/Source/Login/View/LoginViewController.swift
  PRTracker/Source/Login/ViewModel/LoginViewModel.swift
  PRTracker/Source/PR_Listing/Model/UserManager.swift
  PRTracker/Supporting/SceneDelegate.swift
  PRTrackerTests/IssueManagerTests.swift
  PRTrackerTests/URLProtocolStub.swift
  PRTrackerTests/UserManagerTests.swift
  Podfile.lock
Labels: 💡Feature

#24 네트워크 요청을 Result 타입으로 반환할 수 있음 (그 외 리뷰 반영)
  PRTracker.xcodeproj/project.pbxproj
  PRTracker/Resource/Base.lproj/Main.storyboard
  PRTracker/Source/Common/Logger.swift
  PRTracker/Source/Common/NetworkService.swift
  PRTracker/Source/Login/Model/GitHubLoginManager.swift
  PRTracker/Source/Login/View/LoginViewController.swift
  PRTracker/Source/PR_Listing/Model/IssueManager.swift
  PRTracker/Source/PR_Listing/Model/UserManager.swift
  PRTrackerTests/GithubLoginManagerTests.swift
  PRTrackerTests/UIApplicationStub.swift
  Podfile.lock
Labels: 💊Refactor

#29 swipe하면 issue를 닫을 수 있음
  PRTracker.xcodeproj/project.pbxproj
  PRTracker.xcodeproj/xcshareddata/xcschemes/PRTracker.xcscheme
  PRTracker/Resource/Base.lproj/Main.storyboard
  PRTracker/Source/Common/Networking/APIRequest.swift
  PRTracker/Source/Common/Networking/APIRequestable.swift
  PRTracker/Source/Common/Networking/NetworkService.swift
  PRTracker/Source/PR_Listing/Model/Issue.swift
  PRTracker/Source/PR_Listing/Model/IssueManager.swift
  PRTracker/Source/PR_Listing/Model/IssueResource.swift
  PRTracker/Source/PR_Listing/Model/IssuesResource.swift
  PRTracker/Source/PR_Listing/Model/Repository.swift
  PRTracker/Source/PR_Listing/Model/User.swift
  PRTracker/Source/PR_Listing/Model/UserManager.swift
  PRTracker/Source/PR_Listing/View/PullListTableViewCell.swift
  PRTracker/Source/PR_Listing/View/PullListViewController.swift
  PRTracker/Source/PR_Listing/ViewModel/IssueListViewModel.swift
  PRTracker/Source/PR_Listing/ViewModel/IssueTableCellViewModel.swift
  PRTracker/Supporting/AppDelegate.swift
  PRTrackerTests/IssueManagerTests.swift
  PRTrackerTests/IssueServiceStub.swift
  PRTrackerTests/URLProtocolStub.swift
  PRTrackerTests/UserManagerTests.swift
  Podfile.lock
Labels: 💡Feature

#31 IssueManager에 이슈 상태 Filter를 지정 요청할 수 있고, 해당 Filter에 맞는 데이터를 불러와서 저장함
  PRTracker.xcodeproj/project.pbxproj
  PRTracker/Source/Common/Networking/APIEndpoint.swift
  PRTracker/Source/Common/Networking/APIRequest.swift
  PRTracker/Source/Common/Storage.swift
  PRTracker/Source/Login/Model/AccessToken.swift
  PRTracker/Source/Login/Model/GetAccessToken.swift
  PRTracker/Source/Login/Model/GitHubLoginManager.swift
  PRTracker/Source/PR_Listing/Model/GetIssues.swift
  PRTracker/Source/PR_Listing/Model/GetUser.swift
  PRTracker/Source/PR_Listing/Model/IssueManager.swift
  PRTracker/Source/PR_Listing/Model/IssuesParameter.swift
  PRTracker/Source/PR_Listing/Model/IssuesResource.swift
  PRTracker/Source/PR_Listing/Model/UpdateIssue.swift
  PRTracker/Source/PR_Listing/Model/UserManager.swift
  PRTracker/Source/PR_Listing/ViewModel/IssueListViewModel.swift
  PRTrackerTests/IssueManagerTests.swift
  PRTrackerTests/IssueServiceStub.swift
  PRTrackerTests/UserManagerTests.swift
Labels: 💡Feature
